const data = [
  {
    id: "CAM-1",
    title: "Update User Profile Page UI",
    description: "Feature Request",
    status: "Todo",
    priority: 1,
    user: "Harsh Navani",
  },
  {
    id: "CAM-2",
    title: "Implement Email Notification System",
    description: "Feature Request",
    status: "Todo",
    priority: 2,
    user: "Arbaaz Sayyed",
  },
  {
    id: "CAM-3",
    title: "Optimize Database Queries for Performance",
    description: "Feature Request",
    status: "In Progress",
    priority: 3,
    user: "Mohit Gupta",
  },
  {
    id: "CAM-4",
    title: "Add Multi-Language Support",
    description: "Feature Request",
    status: "Todo",
    priority: 4,
    user: "Anoop Sharma",
  },
  {
    id: "CAM-5",
    title:
      "Add Multi-Language Support - Enable multi-language support within the application",
    description: "Feature Request",
    status: "Todo",
    priority: 1,
    user: "Akanksha Punjabi",
  },
  {
    id: "CAM-6",
    title: "Enhance Search Functionality",
    description: "Feature Request",
    status: "Done",
    priority: 3,
    user: "Mohit Gupta",
  },
  {
    id: "CAM-7",
    title: "Integrate Third-Party Payment Gateway",
    description: "Feature Request",
    status: "Done",
    priority: 2,
    user: "Arbaaz Sayyed",
  },
  {
    id: "CAM-8",
    title: "Create Onboarding Tutorial for New Users",
    description: "Feature Request",
    status: "Todo",
    priority: 3,
    user: "Abhideep Maity",
  },
  {
    id: "CAM-9",
    title: "Implement Role-Based Access Control (RBAC)",
    description: "Feature Request",
    status: "Done",
    priority: 2,
    user: "Neha Gupta",
  },
  {
    id: "CAM-10",
    title: "Upgrade Server Infrastructure",
    description: "Feature Request",
    status: "Done",
    priority: 1,
    user: "Mohit Sharma",
  },
  {
    id: "CAM-11",
    title: "Conduct Security Vulnerability Assessment",
    description: "Feature Request",
    status: "Done",
    priority: 4,
    user: "Arbaaz Sayyed",
  },
];

export default data;
